//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hni.Diagnostic.Gathering
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostic
    {
        public long DiagnosticID { get; set; }
        public string DiagnosticSource { get; set; }
        public System.DateTime DiagnosticDateTime { get; set; }
        public string DiagnosticDescription { get; set; }
        public string DiagnosticData { get; set; }
    }
}
